version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build: . 
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db init
        airflow users create \
          --username admin \
          --firstname John \
          --lastname Doe \
          --role Admin \
          --email admin@example.com \
          --password airflow

  webserver:
    build: . 
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - "C:/Users/zayna/Desktop/fitness-data-pipeline:/fitness-data-pipeline"
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: . 
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - "C:/Users/zayna/Desktop/fitness-data-pipeline:/fitness-data-pipeline"
      - "C:/Users/zayna/.dbt:/home/airflow/.dbt"
   
    command: scheduler

volumes:
  postgres_data:
