version: 2

sources:
  - name: fitness_data
    database: "{{ env_var('GCP_PROJECT_ID') }}"  # Use environment variable
    schema: fitness_data  #  dataset in BigQuery
    tables:
      - name: fitness_metrics  #  raw fitness data table